# Generated by Django 5.1.4 on 2024-12-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100)),
                ('real_name', models.CharField(default='[DATA EXPUNGED], [Classified]', max_length=100)),
                ('agent_type', models.CharField(choices=[('S', 'Spy'), ('A', 'Assassin'), ('C', 'Covert Operative'), ('E', 'Enforcer'), ('U', 'Undercover Agent'), ('R', 'Recruiter'), ('H', 'Handler'), ('L', 'Logistics Specialist'), ('W', 'Weapons Specialist'), ('T', 'Tech Specialist')], default='S', max_length=1)),
                ('experience_level', models.CharField(choices=[('N', 'Novice'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Expert'), ('M', 'Master')], default='N', max_length=1)),
                ('gender', models.CharField(default='Unknown', max_length=100)),
                ('age', models.IntegerField(default=47)),
                ('height_cm', models.IntegerField(default=174)),
                ('weight_kg', models.IntegerField(default=64)),
                ('place_of_birth', models.CharField(default='[REDACTED]', max_length=100)),
                ('region', models.CharField(default='[DATA EXPUNGED], [Classified]', max_length=100)),
                ('tagline', models.TextField(max_length=250)),
                ('description', models.TextField(default='[DATA EXPUNGED], [Classified]', max_length=1000)),
                ('previous_agency', models.CharField(default='[REDACTED]', max_length=100)),
            ],
        ),
    ]
