# Generated by Django 5.1.4 on 2024-12-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_agent_age_alter_agent_height_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('S', 'Spy'), ('A', 'Assassin'), ('C', 'Covert Operative'), ('E', 'Enforcer'), ('U', 'Undercover Agent'), ('R', 'Recruiter'), ('H', 'Handler'), ('L', 'Logistics Specialist'), ('W', 'Weapons Specialist'), ('T', 'Tech Specialist')], default=('S', 'Spy'), max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='experience_level',
            field=models.CharField(choices=[('N', 'Novice'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Expert'), ('M', 'Master')], default=('N', 'Novice'), max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=151),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[DATA EXPUNGED], [Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[DATA EXPUNGED], [Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(default='[DATA EXPUNGED], [Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=56),
        ),
    ]
