# Generated by Django 5.1.4 on 2024-12-09 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_agent_age_alter_agent_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=39),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('S', 'Spy'), ('A', 'Assassin'), ('C', 'Covert Operative'), ('E', 'Enforcer'), ('U', 'Undercover Agent'), ('R', 'Recruiter'), ('H', 'Handler'), ('L', 'Logistics Specialist'), ('W', 'Weapons Specialist'), ('T', 'Tech Specialist'), ('P', 'Sleeper Agent')], default=('S', 'Spy'), max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[DATA EXPUNGED]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=165),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=58),
        ),
    ]
