# Generated by Django 5.1.4 on 2024-12-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_agent_user_alter_agent_age_alter_agent_agent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='race_or_ethnicity',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=186),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=79),
        ),
    ]
