# Generated by Django 5.1.4 on 2024-12-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_agent_race_or_ethnicity_alter_agent_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('S', 'Spy'), ('A', 'Assassin'), ('C', 'Covert Operative'), ('E', 'Enforcer'), ('U', 'Undercover Agent'), ('R', 'Recruiter'), ('H', 'Handler'), ('L', 'Logistics Specialist'), ('W', 'Weapons Specialist'), ('T', 'Tech Specialist'), ('P', 'Sleeper Agent')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[REDACTED]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='experience_level',
            field=models.CharField(choices=[('N', 'Novice'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Expert'), ('M', 'Master')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[Undisclosed]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='race_or_ethnicity',
            field=models.CharField(choices=[('R', '[REDACTED]'), ('W', 'White/Caucasian'), ('B', 'Black/African Descent'), ('E', 'East Asian'), ('S', 'South Asian/Desi'), ('M', 'Middle Eastern/Semitic'), ('L', 'Latino/Hispanic'), ('I', 'Indigenous/Native '), ('O', 'Other/Mixed')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=97),
        ),
    ]
