# Generated by Django 5.1.4 on 2024-12-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_agent_gadgets_alter_agent_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[Undisclosed]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=157),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='race_or_ethnicity',
            field=models.CharField(choices=[('R', '[Classified]'), ('W', 'White/Caucasian'), ('B', 'Black/African Descent'), ('E', 'East Asian'), ('S', 'South Asian/Desi'), ('M', 'Middle Eastern/Semitic'), ('L', 'Latino/Hispanic'), ('I', 'Indigenous/Native '), ('O', 'Other/Mixed')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[Undisclosed]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
