# Generated by Django 5.1.4 on 2024-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_agent_age_alter_agent_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=255)),
                ('debrief', models.TextField(default='[Undisclosed]', max_length=7000)),
                ('location', models.CharField(default='[REDACTED]', max_length=255)),
                ('objective', models.CharField(default='[Clearence Required]', max_length=255)),
                ('urgency', models.CharField(choices=[('R', '[Undisclosed]'), ('T', 'Trivial'), ('L', 'Low Priority'), ('M', 'Medium Priority'), ('H', 'High Priority'), ('C', 'Critical'), ('E', 'Emergency')], default='R', max_length=1)),
                ('client', models.CharField(max_length=255)),
                ('mission_type', models.CharField(choices=[('U', 'Unspecified'), ('R', 'Reconnaissance'), ('E', 'Extraction'), ('A', 'Assassination'), ('S', 'Sabotage'), ('O', 'Covert/Black Ops'), ('I', 'Infiltration'), ('D', 'Diplomatic Escort'), ('P', 'Protection Detail'), ('T', 'Training Mission'), ('U', 'Undercover Operation')], default='U', max_length=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[Classified]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(default='[Undisclosed]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=186),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='race_or_ethnicity',
            field=models.CharField(choices=[('R', '[Undisclosed]'), ('W', 'White/Caucasian'), ('B', 'Black/African Descent'), ('E', 'East Asian'), ('S', 'South Asian/Desi'), ('M', 'Middle Eastern/Semitic'), ('L', 'Latino/Hispanic'), ('I', 'Indigenous/Native '), ('O', 'Other/Mixed')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=94),
        ),
    ]
