# Generated by Django 5.1.4 on 2024-12-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_mission_options_alter_agent_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='agents',
            field=models.ManyToManyField(to='main_app.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[REDACTED]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(default='[Undisclosed]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=167),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[Clearence Required]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[Undisclosed]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=61),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objective',
            field=models.CharField(default='[Classified]', max_length=255),
        ),
    ]
