# Generated by Django 5.1.4 on 2024-12-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_agent_age_alter_agent_height_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=43),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[Classified]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=198),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='race_or_ethnicity',
            field=models.CharField(choices=[('R', '[Clearence Required]'), ('W', 'White/Caucasian'), ('B', 'Black/African Descent'), ('E', 'East Asian'), ('S', 'South Asian/Desi'), ('M', 'Middle Eastern/Semitic'), ('L', 'Latino/Hispanic'), ('I', 'Indigenous/Native '), ('O', 'Other/Mixed')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[Classified]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=53),
        ),
        migrations.AlterField(
            model_name='mission',
            name='urgency',
            field=models.CharField(choices=[('R', '[Clearence Required]'), ('T', 'Trivial'), ('L', 'Low Priority'), ('M', 'Medium Priority'), ('H', 'High Priority'), ('C', 'Critical'), ('E', 'Emergency')], default='R', max_length=1),
        ),
    ]
