# Generated by Django 5.1.4 on 2024-12-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_agent_age_alter_agent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[Undisclosed]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(default='[Clearence Required]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=158),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='race_or_ethnicity',
            field=models.CharField(choices=[('R', '[Classified]'), ('W', 'White/Caucasian'), ('B', 'Black/African Descent'), ('E', 'East Asian'), ('S', 'South Asian/Desi'), ('M', 'Middle Eastern/Semitic'), ('L', 'Latino/Hispanic'), ('I', 'Indigenous/Native '), ('O', 'Other/Mixed')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[Undisclosed]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=58),
        ),
        migrations.AlterField(
            model_name='mission',
            name='debrief',
            field=models.TextField(default='[REDACTED]', max_length=7000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objective',
            field=models.CharField(default='[Clearence Required]', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='urgency',
            field=models.CharField(choices=[('R', '[Classified]'), ('T', 'Trivial'), ('L', 'Low Priority'), ('M', 'Medium Priority'), ('H', 'High Priority'), ('C', 'Critical'), ('E', 'Emergency')], default='R', max_length=1),
        ),
    ]
