# Generated by Django 5.1.4 on 2024-12-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_agent_age_alter_agent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(default='[FORBIDDEN]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(default='[DATA EXPUNGED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[ACCESS DENIED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(default='[CONFIDENTIAL]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(default='[REDACTED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=93),
        ),
        migrations.AlterField(
            model_name='mission',
            name='debrief',
            field=models.TextField(default='[SECURED]', max_length=7000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.CharField(default='[INTERNAL USE ONLY]', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objective',
            field=models.CharField(default='[CLEARANCE REQUIRED]', max_length=255),
        ),
    ]
