# Generated by Django 5.1.4 on 2024-12-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_agent_age_alter_agent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=38),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(default='[PROTECTED DATA]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='height_cm',
            field=models.IntegerField(default=190),
        ),
        migrations.AlterField(
            model_name='agent',
            name='place_of_birth',
            field=models.CharField(default='[CLEARANCE REQUIRED]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='previous_agency',
            field=models.CharField(default='[INTERNAL USE ONLY]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='race_or_ethnicity',
            field=models.CharField(choices=[('R', '[FORBIDDEN]'), ('W', 'White/Caucasian'), ('B', 'Black/African Descent'), ('E', 'East Asian'), ('S', 'South Asian/Desi'), ('M', 'Middle Eastern/Semitic'), ('L', 'Latino/Hispanic'), ('I', 'Indigenous/Native '), ('O', 'Other/Mixed')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(default='[INTERNAL USE ONLY]', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='weight_kg',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='mission',
            name='debrief',
            field=models.TextField(default='[FORBIDDEN]', max_length=7000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.CharField(default='[SENSITIVE INFORMATION]', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objective',
            field=models.CharField(default='[SENSITIVE INFORMATION]', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='urgency',
            field=models.CharField(choices=[('R', '[FORBIDDEN]'), ('T', 'Trivial'), ('L', 'Low Priority'), ('M', 'Medium Priority'), ('H', 'High Priority'), ('C', 'Critical'), ('E', 'Emergency')], default='R', max_length=1),
        ),
    ]
